---
spring:
  profiles:
      active: QA

# Set up for Docker environment
# Run a specific environment as SPRING_PROFILES_ACTIVE=QA ./gradlew bootRun
---
spring:
    profiles: dev
    jpa:
        hibernate:
            ddl-auto: create
            # Naming strategy
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

    datasource:
        url: jdbc:mysql://localhost:3306/carwash-db
        username: root
        #password: infoware
        driver-class-name: com.mysql.jdbc.Driver
        testOnBorrow: true
        maxActive: 100
        maxIdle: 100
        minIdle: 10
        testOnReturn: true
        testWhileIdle: true
        properties:
           hibernate:
               # The SQL dialect makes Hibernate generate better SQL for the chosen database
               dialect: org.hibernate.dialect.MySQL5Dialect

           jadira:
             usertype:
                 # Enable JPA to use Joda Time library
                 autoRegisterUserTypes: true
                 # Enable the currency for the JPA to create the table
                 currencyCode: ZAR
---
spring:
    profiles: QA
    jpa:
        hibernate:
            ddl-auto: create
            # Naming strategy
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

    datasource:
        url: jdbc:mysql://textbook-db:3306/carwash-db
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: books
        testWhileIdle: true
        properties:
           hibernate:
               # The SQL dialect makes Hibernate generate better SQL for the chosen database
               dialect: org.hibernate.dialect.MySQL5Dialect

           jadira:
             usertype:
                 # Enable JPA to use Joda Time library
                 autoRegisterUserTypes: true
                 # Enable the currency for the JPA to create the table
                 currencyCode: ZAR
---

server:
    port: 9100

#spring:
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/springbootdb
#    username: postgres
#    password: postgres
#    driverClassName: org.postgresql.Driver
